config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                     Controller#Action
#                     root GET    /                               pages#home
#                     cars GET    /cars(.:format)                 cars#index
#                          POST   /cars(.:format)                 cars#create
#                  new_car GET    /cars/new(.:format)             cars#new
#                 edit_car GET    /cars/:id/edit(.:format)        cars#edit
#                      car GET    /cars/:id(.:format)             cars#show
#                          PATCH  /cars/:id(.:format)             cars#update
#                          PUT    /cars/:id(.:format)             cars#update
#                          DELETE /cars/:id(.:format)             cars#destroy
#          browse_vehicles GET    /browse-vehicles(.:format)      cars#browse
#              car_details GET    /vehicles/:id/details(.:format) cars#details
#         new_user_session GET    /users/sign_in(.:format)        devise/sessions#new
#             user_session POST   /users/sign_in(.:format)        devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)       devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)   devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)  devise/passwords#edit
#            user_password PATCH  /users/password(.:format)       devise/passwords#update
#                          PUT    /users/password(.:format)       devise/passwords#update
#                          POST   /users/password(.:format)       devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)         devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)        devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)           devise/registrations#edit
#        user_registration PATCH  /users(.:format)                devise/registrations#update
#                          PUT    /users(.:format)                devise/registrations#update
#                          DELETE /users(.:format)                devise/registrations#destroy
#                          POST   /users(.:format)                devise/registrations#create
#

Rails.application.routes.draw do

  resources :availabilities
  resources :testimonials
  root to: 'pages#home'

  devise_for :users
  resources :logins
  resources :registers
  resources :contracts
  resources :cars
  resources :owner_ratings
  resources :car_ratings

  #All of Sheldon Ebron's Home Pages (Not used in most casses will probably delete later)
  #--------------------------------------------------------------
  get 'messaging/home', to: 'messages#home', as: 'messages_home'
  get 'communications/home', to: 'communications#home', as: 'communications_home'
  get 'conversations/home', to: 'conversations#home', as: 'conversations_home'

  #All of Sheldon Ebron's Index Pages
  #--------------------------------------------------------------
  get 'messaging', to: 'messages#index', as: 'messages'
  get 'communications', to: 'communications#index', as: 'communications'
  get 'conversations', to: 'conversations#index', as: 'conversations'
  get 'rate_renters', to: 'rate_renters#index', as: 'rate_renters'

  #All of Sheldon Ebron's New Routes
  #--------------------------------------------------------------
  get 'messaging/new', to: 'messages#new', as: 'new_message'
  get 'communications/new', to: 'communications#new', as: 'new_communication'
  get 'conversations/new', to: 'conversations#new', as: 'new_conversation'
  get 'rate_renters/new', to: 'rate_renters#new', as: 'new_rate_renters'

  #All of Sheldon Ebron's New Routes
  #--------------------------------------------------------------
  post 'messaging', to: 'messages#create'
  post 'communications', to: 'communications#create'
  post 'conversations', to: 'conversations#create'
  get 'rate_renters', to: 'rate_renters#create'



  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  get 'messaging/:id', to: 'messages#show', as: 'message'
  get 'communications/:id', to: 'communications#show', as: 'communication'
  get 'conversations/:id', to: 'conversations#show', as: 'conversation'



  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  get 'messaging/:id/edit', to: 'messages#edit', as: 'edit_messages'
  get 'communications/:id/edit', to: 'communications#edit', as: 'edit_communications'
  get 'conversations/:id/edit', to: 'conversations#edit', as: 'edit_conversations'

  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  put 'messaging/:id', to: 'messages#update'
  put 'communications/:id', to: 'communications#update'
  put 'conversations/:id', to: 'conversations#update'


  post 'conversations/:id', to: 'conversations#create_send'

  #All of Sheldon Ebron's update Routes
  #--------------------------------------------------------------
  patch 'messaging/:id', to: 'messages#update'
  patch 'communications/:id', to: 'communications#update'
  patch 'conversations/:id', to: 'conversations#update'

  #All of Sheldon Ebron's Destroy which connectes to controller but no new route
  #--------------------------------------------------------------
  delete 'messaging/:id', to: 'messages#destroy'
  delete 'communications/:id', to: 'communications#destroy'
  delete 'conversations/:id', to: 'conversations#destroy'
  #--------------------------------------------------------------

  get '/browse-vehicles', to: 'cars#browse', as: 'browse_vehicles'
  get '/vehicles/:id/details', to: 'cars#details', as: 'car_details'

  get '/vehicles/:id/history', to: 'cars#history', as: 'car_history'

  get '/my-contracts', to: 'contracts#mycontracts', as: 'my_contracts'
  
  post 'contracts/:id/approve', to: 'contracts#update_status', as: 'approve_contract'
  get '/myreviews', to: 'reviews#myreviews', as: 'my_reviews'
  get '/mytestimonial', to: 'testimonials#mytestimonial', as: 'my_testimonial'
  get '/mycarstatus', to: 'availabilities#mycarstatus', as: 'my_carstatus'

  get 'profiles', to: 'profiles#index', as: 'profiles'
  get 'profiles/myprofile', to: 'profiles#myprofile', as: 'my_profile'
  get 'profiles/new', to: 'profiles#new', as: 'new_profile'
  post 'profiles', to: 'profiles#create'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  #get 'profiles/:id', to: 'profiles#show', as: 'profile'
  #get 'profiles/:id', to: 'users#show', as: 'profile'
  get 'profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  get '/profiles/:id/history', to: 'profiles#history', as: 'profile_history'

  put 'profiles/:id', to: 'profiles#update'
  patch 'profiles/:id', to: 'profiles#update'

  get 'paypals', to: 'paypals#index', as: 'paypals'
  get 'paypals/mypaypal', to: 'paypals#mypaypal', as: 'my_paypal'

  get 'paypals/new', to: 'paypals#new', as: 'new_paypal'
  post 'paypals', to: 'paypals#create'
  get 'paypals/:id', to: 'paypals#show', as: 'paypal'
  get 'paypals/:id/edit', to: 'paypals#edit', as: 'edit_paypal'
  put 'paypals/:id', to: 'paypals#update'
  patch 'paypals/:id', to: 'paypals#update'

  
  post '//reviewpostbyrenter' , to: 'reviewrenters#reviewpostbyrenter' , as: 'review_post'
  get '/about', to: 'pages#about', as: 'about_us'

end

app/models/owner_rating.rb
# == Schema Information
#
# Table name: owner_ratings
#
#  id          :integer          not null, primary key
#  rating      :integer
#  comment     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  owner_id    :integer
#  contract_id :integer
#
# Indexes
#
#  index_owner_ratings_on_contract_id  (contract_id)
#  index_owner_ratings_on_owner_id     (owner_id)
#  index_owner_ratings_on_user_id      (user_id)
#

class OwnerRating < ApplicationRecord
    belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
    belongs_to :user, class_name: 'User', foreign_key: 'user_id'
    belongs_to :contract

   scope :by_owner, -> (owner) {where(owner: owner)}
   scope :by_user, -> (user) {where(user: user)}

end

app/controllers/owner_ratings_controller.rb
class OwnerRatingsController < ApplicationController
  before_action :set_owner_rating, only: [:show, :edit, :update, :destroy]

  # GET /owner_ratings
  # GET /owner_ratings.json
  def index
    @owner_ratings = OwnerRating.all
  end
 
  # GET /owner_ratings/1
  # GET /owner_ratings/1.json
  def show
  end

  # GET /owner_ratings/new
  def new
    @owner_rating = OwnerRating.new
  end

  # GET /owner_ratings/1/edit
  def edit
  end

  # POST /owner_ratings
  # POST /owner_ratings.json
  def create
    @owner_rating = OwnerRating.new(owner_rating_params)

    respond_to do |format|
      if @owner_rating.save
        format.html { redirect_to @owner_rating, notice: 'Owner rating was successfully created.' }
        format.json { render :show, status: :created, location: @owner_rating }
      else
        format.html { render :new }
        format.json { render json: @owner_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owner_ratings/1
  # PATCH/PUT /owner_ratings/1.json
  def update
    respond_to do |format|
      if @owner_rating.update(owner_rating_params)
        format.html { redirect_to @owner_rating, notice: 'Owner rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner_rating }
      else
        format.html { render :edit }
        format.json { render json: @owner_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owner_ratings/1
  # DELETE /owner_ratings/1.json
  def destroy
    @owner_rating.destroy
    respond_to do |format|
      format.html { redirect_to owner_ratings_url, notice: 'Owner rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner_rating
      @owner_rating = OwnerRating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_rating_params
      params.require(:owner_rating).permit(:rating, :comment, :owner_id, :user_id, :contract_id)
    end
end

app/helpers/owner_ratings_helper.rb
module OwnerRatingsHelper
end

app/views/owner_ratings/_form.html.erb
<%= form_with(model: owner_rating, local: true) do |form| %>
  <% if owner_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(owner_rating.errors.count, "error") %> prohibited this owner_rating from being saved:</h2>

      <ul>
      <% owner_rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container my-4">
    <h3>Rating for Owner</h3>
    <div class="form-group col-md-6">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :user_id, class: "form-control" %>
  </div>
  <div class="form-group col-md-6">
      <%= form.label :owner_id %>
      <%= form.text_field :owner_id, id: :owner_id, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :contract_id %>
      <%= form.text_field :contract_id, id: :contract_id, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :owner %>
      <%= form.text_field :owner, id: :owner, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :rating %>
      <%= form.text_field :rating, id: :rating, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :comment %>
      <%= form.text_field :comment, id: :comment, class: "form-control" %>
    </div>
  </div>
  
  <div class="container col-md-4 col-offset-md-4">
    <div class="actions">
      <%= form.submit class: "btn btn-primary btn-block" %>
    </div>
  </div>

<% end %>

app/views/owner_ratings/edit.html.erb
<h1>Editing Owner Rating</h1>

<%= render 'form', owner_rating: @owner_rating %>

<%= link_to 'Show', @owner_rating %> |
<%= link_to 'Back', owner_ratings_path %>

app/views/owner_ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Owner Ratings</h1>

<table>
  <thead>
    <tr>
    <th> Owner </th>
    <th> User </th>
    <th> Rating </th>
    <th> Comments </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owner_ratings.each do |owner_rating| %>
      <tr>
      <td><%= owner_rating.owner.email %></td>
      <td><%= owner_rating.user.email %></td>
      <td><%= owner_rating.rating %></td>
      <td><%= owner_rating.comment %></td>
        <td><%= link_to 'Show', owner_rating %></td>
        <td><%= link_to 'Edit', edit_owner_rating_path(owner_rating) %></td>
        <td><%= link_to 'Destroy', owner_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner Rating', new_owner_rating_path %> 

app/views/owner_ratings/new.html.erb
<h1>New Owner Rating</h1>

<%= render 'form', owner_rating: @owner_rating %>

<%= link_to 'Back', owner_ratings_path %>

app/views/owner_ratings/show.html.erb
<p id="notice"><%= notice %></p>
<p>
      <strong>Owner:</strong>
      <%= @owner_rating.owner.email %>
    </p>
<p>
    <strong>User:</strong>
    <%= @owner_rating.user.email %>
  </p>

<p>
    <strong>Rating:</strong>
    <%= @owner_rating.rating %>
  </p>
<p>
  <strong>Comment:</strong>
  <%= @owner_rating.comment %>
</p>

    <% if @owner_rating.user == current_user %> 
    
    

   <%= link_to 'Edit', edit_owner_rating_path(@owner_rating) %> 
<% end %>  
<%= link_to 'Back', owner_ratings_path %>