config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                     Controller#Action
#                     root GET    /                               pages#home
#                     cars GET    /cars(.:format)                 cars#index
#                          POST   /cars(.:format)                 cars#create
#                  new_car GET    /cars/new(.:format)             cars#new
#                 edit_car GET    /cars/:id/edit(.:format)        cars#edit
#                      car GET    /cars/:id(.:format)             cars#show
#                          PATCH  /cars/:id(.:format)             cars#update
#                          PUT    /cars/:id(.:format)             cars#update
#                          DELETE /cars/:id(.:format)             cars#destroy
#          browse_vehicles GET    /browse-vehicles(.:format)      cars#browse
#              car_details GET    /vehicles/:id/details(.:format) cars#details
#         new_user_session GET    /users/sign_in(.:format)        devise/sessions#new
#             user_session POST   /users/sign_in(.:format)        devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)       devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)   devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)  devise/passwords#edit
#            user_password PATCH  /users/password(.:format)       devise/passwords#update
#                          PUT    /users/password(.:format)       devise/passwords#update
#                          POST   /users/password(.:format)       devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)         devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)        devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)           devise/registrations#edit
#        user_registration PATCH  /users(.:format)                devise/registrations#update
#                          PUT    /users(.:format)                devise/registrations#update
#                          DELETE /users(.:format)                devise/registrations#destroy
#                          POST   /users(.:format)                devise/registrations#create
#

Rails.application.routes.draw do

  resources :availabilities
  resources :testimonials
  root to: 'pages#home'

  devise_for :users
  resources :logins
  resources :registers
  resources :contracts
  resources :cars
  resources :owner_ratings
  resources :car_ratings

  #All of Sheldon Ebron's Home Pages (Not used in most casses will probably delete later)
  #--------------------------------------------------------------
  get 'messaging/home', to: 'messages#home', as: 'messages_home'
  get 'communications/home', to: 'communications#home', as: 'communications_home'
  get 'conversations/home', to: 'conversations#home', as: 'conversations_home'

  #All of Sheldon Ebron's Index Pages
  #--------------------------------------------------------------
  get 'messaging', to: 'messages#index', as: 'messages'
  get 'communications', to: 'communications#index', as: 'communications'
  get 'conversations', to: 'conversations#index', as: 'conversations'
  get 'rate_renters', to: 'rate_renters#index', as: 'rate_renters'

  #All of Sheldon Ebron's New Routes
  #--------------------------------------------------------------
  get 'messaging/new', to: 'messages#new', as: 'new_message'
  get 'communications/new', to: 'communications#new', as: 'new_communication'
  get 'conversations/new', to: 'conversations#new', as: 'new_conversation'
  get 'rate_renters/new', to: 'rate_renters#new', as: 'new_rate_renters'

  #All of Sheldon Ebron's New Routes
  #--------------------------------------------------------------
  post 'messaging', to: 'messages#create'
  post 'communications', to: 'communications#create'
  post 'conversations', to: 'conversations#create'
  get 'rate_renters', to: 'rate_renters#create'



  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  get 'messaging/:id', to: 'messages#show', as: 'message'
  get 'communications/:id', to: 'communications#show', as: 'communication'
  get 'conversations/:id', to: 'conversations#show', as: 'conversation'



  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  get 'messaging/:id/edit', to: 'messages#edit', as: 'edit_messages'
  get 'communications/:id/edit', to: 'communications#edit', as: 'edit_communications'
  get 'conversations/:id/edit', to: 'conversations#edit', as: 'edit_conversations'

  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  put 'messaging/:id', to: 'messages#update'
  put 'communications/:id', to: 'communications#update'
  put 'conversations/:id', to: 'conversations#update'


  post 'conversations/:id', to: 'conversations#create_send'

  #All of Sheldon Ebron's update Routes
  #--------------------------------------------------------------
  patch 'messaging/:id', to: 'messages#update'
  patch 'communications/:id', to: 'communications#update'
  patch 'conversations/:id', to: 'conversations#update'

  #All of Sheldon Ebron's Destroy which connectes to controller but no new route
  #--------------------------------------------------------------
  delete 'messaging/:id', to: 'messages#destroy'
  delete 'communications/:id', to: 'communications#destroy'
  delete 'conversations/:id', to: 'conversations#destroy'
  #--------------------------------------------------------------

  get '/browse-vehicles', to: 'cars#browse', as: 'browse_vehicles'
  get '/vehicles/:id/details', to: 'cars#details', as: 'car_details'

  get '/vehicles/:id/history', to: 'cars#history', as: 'car_history'

  get '/my-contracts', to: 'contracts#mycontracts', as: 'my_contracts'
  
  post 'contracts/:id/approve', to: 'contracts#update_status', as: 'approve_contract'
  get '/myreviews', to: 'reviews#myreviews', as: 'my_reviews'
  get '/mytestimonial', to: 'testimonials#mytestimonial', as: 'my_testimonial'
  get '/mycarstatus', to: 'availabilities#mycarstatus', as: 'my_carstatus'

  get 'profiles', to: 'profiles#index', as: 'profiles'
  get 'profiles/myprofile', to: 'profiles#myprofile', as: 'my_profile'
  get 'profiles/new', to: 'profiles#new', as: 'new_profile'
  post 'profiles', to: 'profiles#create'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  #get 'profiles/:id', to: 'profiles#show', as: 'profile'
  #get 'profiles/:id', to: 'users#show', as: 'profile'
  get 'profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  get '/profiles/:id/history', to: 'profiles#history', as: 'profile_history'

  put 'profiles/:id', to: 'profiles#update'
  patch 'profiles/:id', to: 'profiles#update'

  get 'paypals', to: 'paypals#index', as: 'paypals'
  get 'paypals/mypaypal', to: 'paypals#mypaypal', as: 'my_paypal'

  get 'paypals/new', to: 'paypals#new', as: 'new_paypal'
  post 'paypals', to: 'paypals#create'
  get 'paypals/:id', to: 'paypals#show', as: 'paypal'
  get 'paypals/:id/edit', to: 'paypals#edit', as: 'edit_paypal'
  put 'paypals/:id', to: 'paypals#update'
  patch 'paypals/:id', to: 'paypals#update'

  
  post '//reviewpostbyrenter' , to: 'reviewrenters#reviewpostbyrenter' , as: 'review_post'
  get '/about', to: 'pages#about', as: 'about_us'

end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                     :integer          not null, primary key
#  drivers_license        :string
#  first_name             :string
#  last_name              :string
#  middle_name            :string
#  backgroundcheck_status :string
#  phone                  :string
#  social_security        :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_id                :integer
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#


class Profile < ApplicationRecord

  belongs_to :user

  validates :drivers_license, length: { is: 9 },  uniqueness: true,  presence: true
  validates :first_name, length: { maximum: 20 }, presence: true
  validates :last_name, length: { maximum: 20 }, presence: true
  validates :middle_name, allow_blank: true, length: { maximum: 10 }
  validates :backgroundcheck_status, inclusion: { in: ['checked', 'processing', 'unchecked'] }, presence: true
  validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "Not a valid 10-digit telephone number" },  presence: true
  validates :social_security, numericality: { only_integer: true, less_than_or_equal_to: 999999999, greater_than_or_equal_to: 100000000 }, presence: true

  def full_name_private
    "#{first_name} #{middle_name} #{last_name}"
  end

  def full_name_public
    "#{first_name} #{last_name}"
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    before_action :set_profile, only: [:show, :edit, :update]

    def index
        @profiles = Profile.all
    end

    def new
        @profile = Profile.new
        # render 'profiles/new.html.erb'
    end

    def create
        @profile = Profile.new(user_id: params[:profile][:user_id],
            drivers_license: params[:profile][:drivers_license],
            first_name: params[:profile][:first_name],
            last_name: params[:profile][:last_name],
            middle_name: params[:profile][:middle_name],
            backgroundcheck_status: params[:profile][:backgroundcheck_status],
            phone: params[:profile][:phone],
            social_security: params[:profile][:social_security])
        if @profile.save
        flash[:notice] = "Profile saved successfully"
        redirect_to my_profile_url
        else
            flash.now[:alert] = "Profile save failed!!!!!"
            render :new
        end
    end


    def history
         @ctr = 0
         @p = 0
         @profile = Profile.find(params[:id])
         @contracts = Contract.all
         @rate_renters = RateRenter.all

   end

    def show
        @profile = Profile.find(params[:id])
        @owner_ratings = OwnerRating.by_owner(@profile.user)
        #@profile = Profile.find(params[:id])
        #render 'profiles/show.html.erb'
    end

    def myprofile
        if user_signed_in?
            @profile = current_user.profile
        else
            @profile = nil
        end
    end

    def edit
        begin
            @profile = Profile.find(params[:id])
        rescue ActiveRecord::RecordNotFound
            flash[:alert] = "Profile could not be found"
            redirect_to my_profile_url and return
        end
    end

    def update
        begin
            @profile = Profile.find(params[:id])
        rescue ActiveRecord::RecordNotFound
            flash[:alert] = "Profile could not be found"
            redirect_to my_profile_url and return
        end
        if @profile.update(user_id: params[:profile][:user_id],
            drivers_license: params[:profile][:drivers_license],
            first_name: params[:profile][:first_name],
            last_name: params[:profile][:last_name],
            middle_name: params[:profile][:middle_name],
            backgroundcheck_status: params[:profile][:backgroundcheck_status],
            phone: params[:profile][:phone],
            social_security: params[:profile][:social_security])

            flash[:notice] = "Profile updated successfully"
            redirect_to my_profile_url
        else
            flash.now[:alert] = "Profile could not be updated"
            render :edit
        end
    end

    private

    def set_profile
        begin
            @profile = Profile.find(params[:id])
        rescue ActiveRecord::RecordNotFound
            redirect_to profiles_url, alert: "Profile not found."
        end
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">

    <h2 class="text-center">Edit Profile Information</h2>

    <%= form_for @profile do |f| %>
        <% if @profile.errors.any? %>
            <div id="error_explanation">
            <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

            <ul>
            <% @profile.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
            </div>
        <% end %>
        
        <div class="form-group">
        <%= f.label :user_id %><br />
        <%= f.text_field :user_id, class: "form-control", value: current_user.id %>
      </div>
      
        <div class="form-group">
          <%= f.label :drivers_license %><br />
          <%= f.text_field :drivers_license, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :first_name %><br />
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :middle_name %><br />
          <%= f.text_field :middle_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :last_name %><br />
          <%= f.text_field :last_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :phone %><br />
          <%= f.text_field :phone, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :social_security %><br />
          <%= f.text_field :social_security, class: "form-control" %>
        </div>

        <%= f.hidden_field :backgroundcheck_status, value: 'checked' %>
        
        <div class="actions">
          <%= f.submit "Update Profile", { class: "btn btn-primary btn-block" } %>
        </div>       
        
    <% end %>

    <div class="links text-center">
        <%= link_to 'Back', my_profile_path %>
    </div>
</div>
</div>
</div>

app/views/profiles/history.html.erb
<p id="notice"><%= notice %></p>

<h1><center>User <%= @profile.first_name %>'s Review History</center></h1>

<style>
     table, th, td {
         text-align: center;
     }
</style>


<center>
     <table>
       <thead>
          <tr bgcolor="#c1cdcd">
               <th>Vender</th>
              <th> Rating</th>
              <th> Comment</th>

         </tr>


       </thead>
       <tbody>

         <% @contracts.each do |contract| %>
          <tr bgcolor="#e0eeee" >

               <%if @profile.user == contract.renter_paypal.user%>
                    <% @rate_renters.each do |rate_renter|%>
                         <% if rate_renter.contract.id == contract.id%>
                              <td><%= rate_renter.contract.owner_paypal.user.profile.first_name%></td>
                              <td> <div class='star-rating' data-score = <%= rate_renter.rating %>></div></td>
                              <td><%= rate_renter.comment%></td>

                         <%end%>

                    <%end%>

               <% end %>
          </tr>
         <% end %>
       </tbody>
     </table>

</center>
<br>

<script>
     $('.star-rating').raty({
     path: '/assets/',
     readOnly: true,
     score: function() {
            return $(this).attr('data-score');
     }
     });
</script>

app/views/profiles/index.html.erb
 
<% if current_user %>
  <h2> Current LoggedIn  : <%= current_user.id %>, <%= current_user.email %> </h2>

 <% end %>    


<h1> Profiles </h1>

<% if current_user.profile.present? %> 

<ul>
<img src=<%= image_path('car_profile.jpg')%> width="500px" width="500px" align="right">
<li><%=link_to"My Paypal", my_paypal_path %> </li>

</ul>
<p> 
<b> Drivers License :</b>
<%= current_user.profile.drivers_license %>
</p>

<p>
<b> First Name :</b>
<%= current_user.profile.first_name%>
</p>

 <p>
 <b> Last Name : </b>
 <%= current_user.profile.last_name%>
</p>
 
 <p>
 <b> Middle Name : </b>
 <%= current_user.profile.middle_name%>
</p>

<p>
 <b> Backgroundcheck Status : </b>
 <%= current_user.profile.backgroundcheck_status%>
</p>

<p>
 <b> Phone : </b>
 <%= current_user.profile.phone%>
</p>

<p>
 <b> Social Security : </b>
 <%= current_user.profile.social_security%>
</p>



<p>
   <%= link_to 'Edit', edit_profile_path(current_user.profile) %> 
</p>

<% else %>
<ul>
<img src=<%= image_path('car_profile.jpg')%> width="500px" width="500px" align="right">
<li><%=link_to" My Paypal", my_paypal_path %> </li>

</ul>


<p>
<h3> You have not created a profile, create one new? </h3>
<%= link_to 'New Profile', new_profile_path %> | 

</p> 
<% end %>

app/views/profiles/myprofile.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <div class="container">
        <h2 class="text-center">My Profile Information</h2>
      
        <% if current_user.profile %> 

          <p>
            <b> Name:</b>
            <%= current_user.profile.full_name_private%>
          </p>

          <p>
            <b> Phone: </b>
            <%= current_user.profile.phone%>
          </p>

          <p>
            <b> Social Security: </b>
            <%= current_user.profile.social_security%>
          </p>

          <p> 
            <b> Drivers License Id:</b>
            <%= current_user.profile.drivers_license %>
          </p>

          <p>
            <b> Background Check Status: </b>
            <%= current_user.profile.backgroundcheck_status%>
          </p>

          <div class="links text-center">
            <%= link_to 'Edit', edit_profile_path(current_user.profile) %> 
          </div>

        <% else %>

          <p class="lead">You have not created a profile. Do you want to create one now?</p>

          <div class="links text-center">
            <%= link_to 'New Profile', new_profile_path %>
          </div>

        <% end %>

      </div>

      <div class="container mt-5">
        <h2 class="text-center">My Paypal Information</h2>

        <% if current_user.paypal %> 

          <p>
            Login to your official Paypal Account:<a href ="https://www.paypal.com/signin?returnUri=https%3A%2F%2Fwww.paypal.com%2Fcgi-bin%2Fwebscr%3fcmd%3d_account"> Click this link </a>
          </p>

          <p> 
            <b>Paypal Id :</b>
            <%= current_user.paypal.paypal_id %>
          </p>

          <p>
            <b> Username :</b>
            <%= current_user.paypal.paypal_username%>
          </p>

          <p>
            <b> Account Routing Number : </b>
            <%= current_user.paypal.paypal_account_routing_number%>
          </p>

          <div class="links text-center">
              <%= link_to 'Edit', edit_paypal_path(current_user.paypal) %> 
          </div>

        <% else %>

          <p class="lead">You have not registed your paypal with us. Do you want to add one now?</p>

          <div class="links text-center">
            <%= link_to 'New Paypal', new_paypal_path %> 
          </div>

        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">

    <h2 class="text-center">Add Profile Information</h2>

    <%= form_for @profile do |f| %>
        <% if @profile.errors.any? %>
            <div id="error_explanation">
            <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

            <ul>
            <% @profile.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
            </div>
        <% end %>
        
        <div class="form-group">
        <%= f.label :user_id %><br />
        <%= f.text_field :user_id, class: "form-control", value: current_user.id %>
      </div>

        <div class="form-group">
          <%= f.label :drivers_license %><br />
          <%= f.text_field :drivers_license, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :first_name %><br />
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :middle_name %><br />
          <%= f.text_field :middle_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :last_name %><br />
          <%= f.text_field :last_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :phone %><br />
          <%= f.text_field :phone, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :social_security %><br />
          <%= f.text_field :social_security, class: "form-control" %>
        </div>

        <%= f.hidden_field :backgroundcheck_status, value: 'checked' %>
        
        <div class="actions">
          <%= f.submit "Add Profile", { class: "btn btn-primary btn-block" } %>
        </div>       
        
    <% end %>

    <div class="links text-center">
        <%= link_to 'Back', my_profile_path %>
    </div>
</div>
</div>
</div>

app/views/profiles/show.html.erb
<% if current_user %>
  <h2> Current LoggedIn  : <%= current_user.id %>, <%= current_user.email %> </h2>

 <% end %>


<h1> Profiles </h1>

<% if current_user.profile.present? %>

<ul>
<img src=<%= image_path('car_profile.jpg')%> width="500px" width="500px" align="right">
<li><%=link_to" Paypal", paypals_path %> </li>

</ul>

<p>
<b> First Name :</b>
<%= current_user.profile.first_name%>
</p>

 <p>
 <b> Last Name : </b>
 <%= current_user.profile.last_name%>
</p>

 <p>
 <b> Middle Name : </b>
 <%= current_user.profile.middle_name%>
</p>

<p>
 <b> Reviews : </b>
 <%= current_user.profile.backgroundcheck_status%>
</p>





   <%= link_to "History", profile_history_path(id: current_user.profile.id) %>
<p>
</p>
<% else %>

<p>
<h3> You have not created a profile, create one new? </h3>
<%= link_to 'New Profile', new_profile_path %> 

</p>
<% end %>