config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                     Controller#Action
#                     root GET    /                               pages#home
#                     cars GET    /cars(.:format)                 cars#index
#                          POST   /cars(.:format)                 cars#create
#                  new_car GET    /cars/new(.:format)             cars#new
#                 edit_car GET    /cars/:id/edit(.:format)        cars#edit
#                      car GET    /cars/:id(.:format)             cars#show
#                          PATCH  /cars/:id(.:format)             cars#update
#                          PUT    /cars/:id(.:format)             cars#update
#                          DELETE /cars/:id(.:format)             cars#destroy
#          browse_vehicles GET    /browse-vehicles(.:format)      cars#browse
#              car_details GET    /vehicles/:id/details(.:format) cars#details
#         new_user_session GET    /users/sign_in(.:format)        devise/sessions#new
#             user_session POST   /users/sign_in(.:format)        devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)       devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)   devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)  devise/passwords#edit
#            user_password PATCH  /users/password(.:format)       devise/passwords#update
#                          PUT    /users/password(.:format)       devise/passwords#update
#                          POST   /users/password(.:format)       devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)         devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)        devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)           devise/registrations#edit
#        user_registration PATCH  /users(.:format)                devise/registrations#update
#                          PUT    /users(.:format)                devise/registrations#update
#                          DELETE /users(.:format)                devise/registrations#destroy
#                          POST   /users(.:format)                devise/registrations#create
#

Rails.application.routes.draw do

  resources :availabilities
  resources :testimonials
  root to: 'pages#home'

  devise_for :users
  resources :logins
  resources :registers
  resources :contracts
  resources :cars
  resources :owner_ratings
  resources :car_ratings

  #All of Sheldon Ebron's Home Pages (Not used in most casses will probably delete later)
  #--------------------------------------------------------------
  get 'messaging/home', to: 'messages#home', as: 'messages_home'
  get 'communications/home', to: 'communications#home', as: 'communications_home'
  get 'conversations/home', to: 'conversations#home', as: 'conversations_home'

  #All of Sheldon Ebron's Index Pages
  #--------------------------------------------------------------
  get 'messaging', to: 'messages#index', as: 'messages'
  get 'communications', to: 'communications#index', as: 'communications'
  get 'conversations', to: 'conversations#index', as: 'conversations'
  get 'rate_renters', to: 'rate_renters#index', as: 'rate_renters'

  #All of Sheldon Ebron's New Routes
  #--------------------------------------------------------------
  get 'messaging/new', to: 'messages#new', as: 'new_message'
  get 'communications/new', to: 'communications#new', as: 'new_communication'
  get 'conversations/new', to: 'conversations#new', as: 'new_conversation'
  get 'rate_renters/new', to: 'rate_renters#new', as: 'new_rate_renters'

  #All of Sheldon Ebron's New Routes
  #--------------------------------------------------------------
  post 'messaging', to: 'messages#create'
  post 'communications', to: 'communications#create'
  post 'conversations', to: 'conversations#create'
  get 'rate_renters', to: 'rate_renters#create'



  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  get 'messaging/:id', to: 'messages#show', as: 'message'
  get 'communications/:id', to: 'communications#show', as: 'communication'
  get 'conversations/:id', to: 'conversations#show', as: 'conversation'



  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  get 'messaging/:id/edit', to: 'messages#edit', as: 'edit_messages'
  get 'communications/:id/edit', to: 'communications#edit', as: 'edit_communications'
  get 'conversations/:id/edit', to: 'conversations#edit', as: 'edit_conversations'

  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  put 'messaging/:id', to: 'messages#update'
  put 'communications/:id', to: 'communications#update'
  put 'conversations/:id', to: 'conversations#update'


  post 'conversations/:id', to: 'conversations#create_send'

  #All of Sheldon Ebron's update Routes
  #--------------------------------------------------------------
  patch 'messaging/:id', to: 'messages#update'
  patch 'communications/:id', to: 'communications#update'
  patch 'conversations/:id', to: 'conversations#update'

  #All of Sheldon Ebron's Destroy which connectes to controller but no new route
  #--------------------------------------------------------------
  delete 'messaging/:id', to: 'messages#destroy'
  delete 'communications/:id', to: 'communications#destroy'
  delete 'conversations/:id', to: 'conversations#destroy'
  #--------------------------------------------------------------

  get '/browse-vehicles', to: 'cars#browse', as: 'browse_vehicles'
  get '/vehicles/:id/details', to: 'cars#details', as: 'car_details'

  get '/vehicles/:id/history', to: 'cars#history', as: 'car_history'

  get '/my-contracts', to: 'contracts#mycontracts', as: 'my_contracts'
  
  post 'contracts/:id/approve', to: 'contracts#update_status', as: 'approve_contract'
  get '/myreviews', to: 'reviews#myreviews', as: 'my_reviews'
  get '/mytestimonial', to: 'testimonials#mytestimonial', as: 'my_testimonial'
  get '/mycarstatus', to: 'availabilities#mycarstatus', as: 'my_carstatus'

  get 'profiles', to: 'profiles#index', as: 'profiles'
  get 'profiles/myprofile', to: 'profiles#myprofile', as: 'my_profile'
  get 'profiles/new', to: 'profiles#new', as: 'new_profile'
  post 'profiles', to: 'profiles#create'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  #get 'profiles/:id', to: 'profiles#show', as: 'profile'
  #get 'profiles/:id', to: 'users#show', as: 'profile'
  get 'profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  get '/profiles/:id/history', to: 'profiles#history', as: 'profile_history'

  put 'profiles/:id', to: 'profiles#update'
  patch 'profiles/:id', to: 'profiles#update'

  get 'paypals', to: 'paypals#index', as: 'paypals'
  get 'paypals/mypaypal', to: 'paypals#mypaypal', as: 'my_paypal'

  get 'paypals/new', to: 'paypals#new', as: 'new_paypal'
  post 'paypals', to: 'paypals#create'
  get 'paypals/:id', to: 'paypals#show', as: 'paypal'
  get 'paypals/:id/edit', to: 'paypals#edit', as: 'edit_paypal'
  put 'paypals/:id', to: 'paypals#update'
  patch 'paypals/:id', to: 'paypals#update'

  
  post '//reviewpostbyrenter' , to: 'reviewrenters#reviewpostbyrenter' , as: 'review_post'
  get '/about', to: 'pages#about', as: 'about_us'

end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user1_id   :integer
#  user2_id   :integer
#
# Indexes
#
#  index_conversations_on_user1_id  (user1_id)
#  index_conversations_on_user2_id  (user2_id)
#

class Conversation < ApplicationRecord

     belongs_to :user1, class_name: 'User', foreign_key: 'user1_id', optional: true
     belongs_to :user2, class_name: 'User', foreign_key: 'user2_id', optional: true
     has_many :communications

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

     #In this index for the Message Controller we are able to look at all the Messages in the table
     def index
          #renders 'alcohols/index.html.erb'
          if current_user.nil?
               redirect_to user_session_path
          else
          @user = current_user
          @conversations = Conversation.all

          end

     end

     def show
          if current_user.nil?
               redirect_to user_session_path
          else
               @user = current_user
               # @communication = Communication.new


               @conversations = Conversation.all
               @conversation = Conversation.find(params[:id])
               @communications = Communication.all

          end
          @message = Message.new
          @communication = Communication.new


     end

     def create_send
          @message= Message.new(message: params[:message][:message])

          if @message.save
             flash[:notice] = 'Conversation saved successfully!'
             redirect_to new_communication_path
          else
             flash.now[:alert] = 'Conversation save failed!'
             render :new
          end
      end








     def new
          if current_user.nil?
               redirect_to user_session_path
          else
          @user = current_user
          @conversations = Conversation.all
          @communications = Communication.all
          @conversation = Conversation.new
          @communication = Communication.new



          end
              #render 'countries/new.html.erb'
     end

     def create

         @conversation= Conversation.new(user1_id: current_user.id,
                                        user2_id: params[:conversation][:user2_id])

         if @conversation.save
            flash[:notice] = 'Conversation saved successfully!'
            redirect_to conversations_url
         else
            flash.now[:alert] = 'Conversation save failed!'
            render :new
         end

     end



     def edit
         @conversation = conversation.find(params[:id])
            #render 'countries/edit.html.erb'
     end

     def update

     end

     def destroy
     end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<style>


<style>

     * {
          margin: 0;
          padding: 0;
          font-family: tahoma, sans-serif;
          box-sizing: border-box;
     }

     body{
          background: white;
     }

     .chatbox{
          width: 500px;
          min-width: 390px;
          height: 600px;
          background: white;
          padding: 25px;
          margin: 20px auto;
          box-shadow: 0 3px grey;
          overflow-y: scroll
     }


     .chatlog{
          padding: 10px;
          width: 100%;
          height: 450px;

     }

     .chat{
          display: flex;
          flex-flow: row wrap;
          align-items: flex-start;
          margin-bottom: 10px;
     }

     .chat .user-photo{
          width: 60px;
          height: 60px;
          background: white;
          border-radius: 0%;

     }

     .chat .chat-message{
          width:80%;
          padding: 15px;
          margin: 5px 10px 0;
          background: blue;
          border-radius: 10px;
          color: white;
          font-size: 18px;
     }

     .friend .chat-message{
          background: blue;
     }

     .self .chat-message{
          background: green;
          order: -1;

     }

     p#losinfo {
     font-size:20px;
     }

     p#losinfo span {
     font-size:15px;
     }
</style>



<div class= "chatbox">
           <div class= "chatlog">
                <% if Communication.all.empty?%>

                <% else %>

                <% Communication.all.each do |communication|  %>
                     <% if conversation.user1.email == communication.sender.email%>
                          <% if conversation.user2.email == communication.reciever.email%>
                               <div class= "chat self">
                                    <div class= "user-photo">
                                    </div>
                                    <p class= "chat-message" id="losinfo">
                                         <span ><%= communication.sender.email %></span><br><%= communication.message.message %></p>


                               </div>
                          <% end %>

                          <% elsif conversation.user1.email == communication.reciever.email%>
                               <% if conversation.user2.email == communication.sender.email%>
                               <div class= "chat friend">
                                      <div class= "user-photo">
                                      </div>
                                      <p class= "chat-message" id="losinfo">
                                           <span ><%= communication.sender.email %></span><br><%= communication.message.message %></p>

                                 </div>
                                 <% end %>

                     <% end %>
                  <% end %>
                  <% end %>


           </div>

      </div>
      <%= link_to "Send New Message", new_communication_path %>

app/views/conversations/_message.html.erb
<style>
html  {
   background: gray;
}

h1 {
   text-align: center;
}

     * {
          margin: 0;
          padding: 0;
          font-family: tahoma, sans-serif;
          box-sizing: border-box;
     }

     body{
          background: white;
     }

     .chatbox{
          width: 500px;
          min-width: 390px;
          height: 600px;
          background: white;
          padding: 25px;
          margin: 20px auto;
          box-shadow: 0 3px grey;

     }


     .chatlog{
          padding: 10px;
          width: 100%;
          height: 450px;

     }

     .chat{
          display: flex;
          flex-flow: row wrap;
          align-items: flex-start;
          margin-bottom: 10px;
     }

     .chat .user-photo{
          width: 60px;
          height: 60px;
          background: grey;
          border-radius: 50%;

     }

     .chat .chat-message{
          width:80%;
          padding: 15px;
          margin: 5px 10px 0;
          background: blue;
          border-radius: 10px;
          color: white;
          font-size: 18px;
     }

     .friend .chat-message{
          background: blue;
     }

     .self .chat-message{
          background: green;
          order: -1;

     }

     p#losinfo {
     font-size:20px;
     }

     p#losinfo span {
     font-size:15px;
     }
</style>



           <%= form_for :Message do |f| %>
           <p>
               Message
               <br>
               <%= f.text_field :message %>

           </p>




           <p>
               <%= f.submit "Add message to the body" %>
           </p>



<%end%>

app/views/conversations/index.html.erb
<!--
    Coded by: Sheldon Ebron
    Email: sebron@memphis.edu
-->

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="pull-right btn-group-sm padding-right =50px">
<a href= <%=new_conversation_path%> class="btn btn-success tooltips" data-placement="top" data-original-title="Add">
    <i class="fa fa-plus"></i>

</a>
</div>
<div class="container bootstrap snippet">

    <div class="row">
         </a>
        <% if @conversations.empty?%>
        <% else %>
              <% @conversations.each do |conversation|  %>
               <% if conversation.user1.email == @user.email %>
                  <div class="col-sm-6">
                      <div class="panel">
                         <div class="panel-body p-t-10">
                              <div class="media-main">
                                  <a class="pull-left" href="#">
                                      <img class="thumb-lg img-circle bx-s" src="https://bootdey.com/img/Content/user_3.jpg" alt="">
                                  </a>
                                  <div class="pull-right btn-group-sm">
                                      <a href=<%=conversation_path(conversation)%> class="btn btn-success tooltips" data-placement="top" data-toggle="tooltip" data-original-title="Edit">
                                          <i class="fa fa-pencil"></i>
                                      </a>

                                  </div>
                                  <div class="info">
                                      <h4><%= conversation.user2.email%>
                                                  </h4>
                                      <p class="text-muted"><%= link_to conversation.user2.email, conversation_path(conversation) %>
                                   </p>
                                  </div>
                              </div>
                              <div class="clearfix"></div>
                              <hr>
                         </div>
                      </div>
                  </div>

                  <%elsif conversation.user2.email == @user.email %>

                  <div class="col-sm-6">
                      <div class="panel">
                         <div class="panel-body p-t-10">
                              <div class="media-main">
                                  <a class="pull-left" href="#">
                                      <img class="thumb-lg img-circle bx-s" src="https://bootdey.com/img/Content/user_3.jpg" alt="">
                                  </a>
                                  <div class="pull-right btn-group-sm">
                                      <a href=<%=conversation_path(conversation)%> class="btn btn-success tooltips" data-placement="top" data-toggle="tooltip" data-original-title="Edit">
                                          <i class="fa fa-pencil"></i>
                                      </a>

                                  </div>
                                  <div class="info">
                                      <h4><%= conversation.user1.email%>
                                                  </h4>
                                      <p class="text-muted"><%= link_to conversation.user1.email, conversation_path(conversation) %>
                                   </p>
                                  </div>
                              </div>
                              <div class="clearfix"></div>
                              <hr>
                         </div>
                      </div>
                  </div>
              </td>

                    <%end%>
               <%end%>
          <%end%>
</div>
</div>

app/views/conversations/new.html.erb
<style>

     h1 {
         text-align: center;
     }
</style>


<div class = "conversation-window">

<h1>New Conversation</h1>

<%= form_for @conversation do |f| %>

        <p>
            <b>Start a Conversation with</b><br>
            <%= f.collection_select(:user2_id, User.all, :id, :email)%>
        </p>
        <p>
            <%= f.submit "Add" %>
        </p>

    <% end %>

</div>

app/views/conversations/show.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>





<div class="pull-right btn-group-sm padding-right =50px">
<a href= <%=new_conversation_path%> class="btn btn-success tooltips" data-placement="top" data-original-title="Add">
    <i class="fa fa-plus"></i>

</a>


</div>
<div class="container bootstrap snippet">
     <div class="dropdown">
       <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        View Conversations
       </button>


       <div class="dropdown-menu">
            <a class="dropdown-item" href= <%=conversations_path%> >View All Conversations</a>


        <% if @conversations.empty?%>
        <% else %>
              <% @conversations.each do |conversation|  %>
               <% if conversation.user1.email == @user.email %>
                   <div class="panel">
                      <div class="panel-body p-t-10">
                           <div class="media-main">
                               <a class="pull-left" href="#">
                                   <img class="thumb-lg img-circle bx-s" src="https://bootdey.com/img/Content/user_3.jpg" alt="">
                               </a>
                               <div class="pull-right btn-group-sm">
                                   <a href=<%=conversation_path(conversation)%> class="btn btn-success tooltips" data-placement="top" data-toggle="tooltip" data-original-title="Edit">
                                       <i class="fa fa-pencil"></i>
                                   </a>

                               </div>
                               <div class="info">

                                   <p class="text-muted"><%= link_to conversation.user2.email, conversation_path(conversation) %>
                                </p>
                               </div>
                           </div>
                           <div class="clearfix"></div>
                           <hr>
                      </div>
                   </div>


                  <%elsif conversation.user2.email == @user.email %>
                      <div class="panel">
                         <div class="panel-body p-t-10">
                              <div class="media-main">
                                  <a class="pull-left" href="#">
                                      <img class="thumb-lg img-circle bx-s" src="https://bootdey.com/img/Content/user_3.jpg" alt="">
                                  </a>
                                  <div class="pull-right btn-group-sm">
                                      <a href=<%=conversation_path(conversation)%> class="btn btn-success tooltips" data-placement="top" data-toggle="tooltip" data-original-title="Edit">
                                          <i class="fa fa-pencil"></i>
                                      </a>

                                  </div>
                                  <div class="info">

                                      <p class="text-muted"><%= link_to conversation.user1.email, conversation_path(conversation) %>
                                   </p>
                                  </div>
                              </div>
                              <div class="clearfix"></div>
                              <hr>
                         </div>
                      </div>
                  </center>

              </td>

                    <%end%>
               <%end%>
          <%end%>


</div>
</div>

</div>
</div>


<div class="container">
  <div class="jumbotron jumbotron-fluid rounded" style="background-image: url(/assets/winding_road_5.jpg); background-size: cover; padding-top: 20%; padding-bottom: 20%" >

    <div class="overlay"></div>
    <div class="container text-center text-light">
      <h1 class="display-3 mb-1 text-light">Conversations</h1>





      <%= render :partial => "conversations/conversation", :locals => {:conversation => @conversation } %>









     </div>
     </div>
  </div>
</div>