config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                     Controller#Action
#                     root GET    /                               pages#home
#                     cars GET    /cars(.:format)                 cars#index
#                          POST   /cars(.:format)                 cars#create
#                  new_car GET    /cars/new(.:format)             cars#new
#                 edit_car GET    /cars/:id/edit(.:format)        cars#edit
#                      car GET    /cars/:id(.:format)             cars#show
#                          PATCH  /cars/:id(.:format)             cars#update
#                          PUT    /cars/:id(.:format)             cars#update
#                          DELETE /cars/:id(.:format)             cars#destroy
#          browse_vehicles GET    /browse-vehicles(.:format)      cars#browse
#              car_details GET    /vehicles/:id/details(.:format) cars#details
#         new_user_session GET    /users/sign_in(.:format)        devise/sessions#new
#             user_session POST   /users/sign_in(.:format)        devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)       devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)   devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)  devise/passwords#edit
#            user_password PATCH  /users/password(.:format)       devise/passwords#update
#                          PUT    /users/password(.:format)       devise/passwords#update
#                          POST   /users/password(.:format)       devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)         devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)        devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)           devise/registrations#edit
#        user_registration PATCH  /users(.:format)                devise/registrations#update
#                          PUT    /users(.:format)                devise/registrations#update
#                          DELETE /users(.:format)                devise/registrations#destroy
#                          POST   /users(.:format)                devise/registrations#create
#

Rails.application.routes.draw do

  resources :availabilities
  resources :testimonials
  root to: 'pages#home'

  devise_for :users
  resources :logins
  resources :registers
  resources :contracts
  resources :cars
  resources :owner_ratings
  resources :car_ratings

  #All of Sheldon Ebron's Home Pages (Not used in most casses will probably delete later)
  #--------------------------------------------------------------
  get 'messaging/home', to: 'messages#home', as: 'messages_home'
  get 'communications/home', to: 'communications#home', as: 'communications_home'
  get 'conversations/home', to: 'conversations#home', as: 'conversations_home'

  #All of Sheldon Ebron's Index Pages
  #--------------------------------------------------------------
  get 'messaging', to: 'messages#index', as: 'messages'
  get 'communications', to: 'communications#index', as: 'communications'
  get 'conversations', to: 'conversations#index', as: 'conversations'
  get 'rate_renters', to: 'rate_renters#index', as: 'rate_renters'

  #All of Sheldon Ebron's New Routes
  #--------------------------------------------------------------
  get 'messaging/new', to: 'messages#new', as: 'new_message'
  get 'communications/new', to: 'communications#new', as: 'new_communication'
  get 'conversations/new', to: 'conversations#new', as: 'new_conversation'
  get 'rate_renters/new', to: 'rate_renters#new', as: 'new_rate_renters'

  #All of Sheldon Ebron's New Routes
  #--------------------------------------------------------------
  post 'messaging', to: 'messages#create'
  post 'communications', to: 'communications#create'
  post 'conversations', to: 'conversations#create'
  get 'rate_renters', to: 'rate_renters#create'



  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  get 'messaging/:id', to: 'messages#show', as: 'message'
  get 'communications/:id', to: 'communications#show', as: 'communication'
  get 'conversations/:id', to: 'conversations#show', as: 'conversation'



  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  get 'messaging/:id/edit', to: 'messages#edit', as: 'edit_messages'
  get 'communications/:id/edit', to: 'communications#edit', as: 'edit_communications'
  get 'conversations/:id/edit', to: 'conversations#edit', as: 'edit_conversations'

  #All of Sheldon Ebron's Show/Find Routes
  #--------------------------------------------------------------
  put 'messaging/:id', to: 'messages#update'
  put 'communications/:id', to: 'communications#update'
  put 'conversations/:id', to: 'conversations#update'


  post 'conversations/:id', to: 'conversations#create_send'

  #All of Sheldon Ebron's update Routes
  #--------------------------------------------------------------
  patch 'messaging/:id', to: 'messages#update'
  patch 'communications/:id', to: 'communications#update'
  patch 'conversations/:id', to: 'conversations#update'

  #All of Sheldon Ebron's Destroy which connectes to controller but no new route
  #--------------------------------------------------------------
  delete 'messaging/:id', to: 'messages#destroy'
  delete 'communications/:id', to: 'communications#destroy'
  delete 'conversations/:id', to: 'conversations#destroy'
  #--------------------------------------------------------------

  get '/browse-vehicles', to: 'cars#browse', as: 'browse_vehicles'
  get '/vehicles/:id/details', to: 'cars#details', as: 'car_details'

  get '/vehicles/:id/history', to: 'cars#history', as: 'car_history'

  get '/my-contracts', to: 'contracts#mycontracts', as: 'my_contracts'
  
  post 'contracts/:id/approve', to: 'contracts#update_status', as: 'approve_contract'
  get '/myreviews', to: 'reviews#myreviews', as: 'my_reviews'
  get '/mytestimonial', to: 'testimonials#mytestimonial', as: 'my_testimonial'
  get '/mycarstatus', to: 'availabilities#mycarstatus', as: 'my_carstatus'

  get 'profiles', to: 'profiles#index', as: 'profiles'
  get 'profiles/myprofile', to: 'profiles#myprofile', as: 'my_profile'
  get 'profiles/new', to: 'profiles#new', as: 'new_profile'
  post 'profiles', to: 'profiles#create'
  get 'profiles/:id', to: 'profiles#show', as: 'profile'
  #get 'profiles/:id', to: 'profiles#show', as: 'profile'
  #get 'profiles/:id', to: 'users#show', as: 'profile'
  get 'profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  get '/profiles/:id/history', to: 'profiles#history', as: 'profile_history'

  put 'profiles/:id', to: 'profiles#update'
  patch 'profiles/:id', to: 'profiles#update'

  get 'paypals', to: 'paypals#index', as: 'paypals'
  get 'paypals/mypaypal', to: 'paypals#mypaypal', as: 'my_paypal'

  get 'paypals/new', to: 'paypals#new', as: 'new_paypal'
  post 'paypals', to: 'paypals#create'
  get 'paypals/:id', to: 'paypals#show', as: 'paypal'
  get 'paypals/:id/edit', to: 'paypals#edit', as: 'edit_paypal'
  put 'paypals/:id', to: 'paypals#update'
  patch 'paypals/:id', to: 'paypals#update'

  
  post '//reviewpostbyrenter' , to: 'reviewrenters#reviewpostbyrenter' , as: 'review_post'
  get '/about', to: 'pages#about', as: 'about_us'

end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id              :integer          not null, primary key
#  make            :string
#  model           :string
#  year            :integer
#  color           :string
#  description     :string
#  category        :string
#  mileage         :string
#  number_of_seats :integer
#  price_per_day   :decimal(10, 2)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#
# Indexes
#
#  index_cars_on_user_id  (user_id)
#

class Car < ApplicationRecord
    include Filterable

    before_save :round_price, :color_case

    belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
    has_many :contracts
    has_many :locations, as: :addressable
    has_many :addresses, through: :locations

    has_many :availabilities

    accepts_nested_attributes_for :locations
    has_many :ratings , class_name: 'CarRating', foreign_key: 'car_rating_id'

    VEHICLE_CATEGORIES = ["SUV", "Truck", "Sedan", "Van", "Coupe", "Wagon", "Convertible", "Sports Car", "Diesal", "Crossover", "Luxury Car", "Hybrid/Electric", "Other"]
    
    validates :make, :model, :year, :color, :description, :category, :mileage, :number_of_seats, :price_per_day, presence: true
    validates :year, numericality: { only_integer: true, greater_than_or_equal_to: 1900, less_than_or_equal_to: Date.current.year + 1 }
    validates :category, inclusion: { in: VEHICLE_CATEGORIES }
    validates :mileage, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 300000 }
    validates :number_of_seats, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 7 }
    validates :price_per_day, format: { with: /\A\d{1,4}(.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 10000 }

    scope :by_make, -> (make) { where(make: make)}
    scope :by_color, -> (color) { where(color: color) }
    scope :by_category, -> (category) { where(category: category)}
    scope :by_pickup_location_zipcode, -> (zipcode) { joins(:pickup_addresses).merge(Address.by_zipcode(zipcode)) }
    
    has_many :current_locations, -> { current_locations }, foreign_key: :addressable_id, class_name: 'Location'
    has_many :pickup_addresses, through: :current_locations, source: :address

    def make_model
        "#{make} #{model}"
    end

    def make_model_year
        "#{make} #{model} (#{year})"
    end

    private
    def round_price
        self.price_per_day = price_per_day.to_f.round(2)
    end

    def color_case
        self.color.downcase!
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, except: [:browse, :details]
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  #before_action :authenticate_user!, only: [:index, :new, :edit, :create, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = current_user.cars
    #@cars = Car.all
  end

  def browse
    #@cars = Car.includes(:pickup_addresses).all

    @colors = Car.distinct.pluck(:color)
    @categories = Car.distinct.pluck(:category)
    @makes = Car.distinct.pluck(:make)
    @cars = Car.includes(:pickup_addresses).filter(params.slice(:by_color, :by_category, :by_make, :by_pickup_location_zipcode))

    # respond_to do |format|
    #   format.html { render :browse }
    #   format.js { render :browse }
    # end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    #@car = current_user.cars.find(params[:id])
  end

  def details
    @car = Car.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    redirect_to browse_vehicles_url, alert: "Car not found."
  end

  def history
       @ctr = 0
       @p = 0
       @car = Car.find(params[:id])
       @contracts = Contract.all
       @rate_renter = RateRenter.all

end
  # GET /cars/new
  def new
    @car = current_user.cars.new
    @locations = @car.locations.build
    @address = @locations.build_address
    #@car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = current_user.cars.new(car_params)
    #@car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      #@car = Car.find(params[:id])
      @car = current_user.cars.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to cars_url, alert: "Car not found."
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      #params.require(:car).permit(:make, :model, :year, :color, :description, :category, :mileage, :number_of_seats, :price_per_day, :user_id, location_ids: [])
      params.require(:car).permit(:make, :model, :year, :color, :description, :category, :mileage,
       :number_of_seats, :price_per_day, :user_id, locations_attributes: [:id, :status, address_attributes: [:id, :street1, :street2, :city, :state, :zipcode]])
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_browse.html.erb

      <div class="container">
        <div class="row justify-content-center">
          <% @cars.each do |car| %>
            <div class="card col-xs-6 col-sm-4 col-md-3 mb-3 px-1" style="min-width: 170px;">
              <img class="card-img-top" src=<%= image_path('car_profile.jpg')%> alt="Car image placeholder">
              <div class="card-body text-center">
                <h5 class="card-title"><%= link_to car.make_model, car_details_path(car) %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= car.year %></h6>
                <p class="card-text"><%= car.color %>, <%= car.pickup_addresses.first.zipcode %>, $<%= car.price_per_day %>/day</p>
              </div>
            </div>
          <% end %>
        </div>
      </div>


app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container my-4">
    <h3>Details</h3>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label :color %>
        <%= form.text_field :color, id: :car_color, class: "form-control" %>
      </div>
      <div class="form-group col-md-6">
        <%= form.label :category %>
        <%= form.select :category, options_for_select(Car::VEHICLE_CATEGORIES, car.category), {}, { class: "form-control" } %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-5">
        <%= form.label :make %>
        <%= form.text_field :make, id: :car_make, class: "form-control" %>
      </div>
      <div class="form-group col-md-5">
        <%= form.label :model %>
        <%= form.text_field :model, id: :car_model, class: "form-control" %>
      </div>
      <div class="form-group col-md-2">
        <%= form.label :year %>
        <%= form.number_field :year, id: :car_year, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, id: :car_description, rows: 3, class: "form-control" %>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <%= form.label :mileage %>
        <%= form.text_field :mileage, id: :car_mileage, class: "form-control" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.label :number_of_seats %>
        <%= form.number_field :number_of_seats, id: :car_number_of_seats, class: "form-control" %>
      </div>
      <div class="form-group col-md-4">
        <%= form.label :price_per_day %>
        <%= form.text_field :price_per_day, id: :car_price_per_day, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="container my-4">
    <h3>Pickup Locations</h3>

    <%= form.fields_for :locations do |location_form| %>
      <%= render 'locations/location_fields', f: location_form %>
    <% end %>
    
    <div class="links">
      <%= link_to_add_association 'Add Pickup Location', form, :locations, partial: 'locations/location_fields', render_options: { wrapper: 'inline' } %>
    </div>
  </div>

  <div class="container col-md-4 col-offset-md-4">
    <div class="actions">
      <%= form.submit class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/cars/browse.html.erb
<div class="container mb-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <h2 class="text-center">Browse Vehicles</h2>

      <div class="container col-md-6 my-4">
        <div class="row justify-content-center border border-primary rounded p-3">
          <%= form_with url: browse_vehicles_path, method: :get do |f| %>
            <div class="form-row">
              <div class="my_filter form-check col-md-3">
                <h5>By Color</h5>
                <ul style="list-style: none; margin-left: -38px;">
                <% @colors.each do |color| %>
                  <li>
                  <%= f.check_box :by_color, { multiple: true }, color, false %>
                  <%= f.label color, class: "checkbox inline" %>
                  </li>
                <% end %>
                </ul>
              </div>
              <div class="my_filter form-check col-md-5">
                <h5>By Vehicle Types</h5>
                <ul style="list-style: none; margin-left: -38px;">
                <% @categories.each do |category| %>
                  <li>
                  <%= f.check_box :by_category, { multiple: true }, category, false %>
                  <%= f.label category, class: "checkbox inline" %>
                  </li>
                <% end %>
                </ul>
              </div>
              <div class="form-group col-md-4">
                <div class="by_category">
                  <%= f.label :by_make, class: "select inline" %>
                  <%= f.select :by_make, @makes, { include_blank: true }, { class: "form-control" }  %>
                </div>
                <div class="by_zipcode mt-2">
                  <%= f.label "By zipcode", class: "textbox inline" %>
                  <%= f.text_field :by_pickup_location_zipcode, class: "form-control" %>
                </div>
              </div>
            </div>
            <%= f.submit "Filter", class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>

      <div id="browse_container">
        <%= render 'browse', cars: @cars %>
      </div>

    </div>
  </div>
</div>

app/views/cars/browse.js.erb
$('#browse_container').html("<%= escape_javascript(render 'browse', collection: @cars) %>");

app/views/cars/details.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <h2 class="text-center"><%= @car.make_model_year %></h2>

      <p>
        <strong>Category:</strong>
        <%= @car.category %>
      </p>

      <p>
        <strong>Color:</strong>
        <%= @car.color %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @car.description %>
      </p>

      <p>
        <strong>Mileage:</strong>
        <%= @car.mileage %>
      </p>

      <p>
        <strong>Number of seats:</strong>
        <%= @car.number_of_seats %>
      </p>

      <p>
        <strong>Price per day: $</strong>
        <%= @car.price_per_day %>
      </p>

      <div class="mt-5">
        <h4>Pickup Location</h4>
        <% @car.locations.each do |location| %>
          <% if location.status == "current"%>
            <p>
              <%= location.address.street1 %><br>
              <%= location.address.short_form %>
            </p>
          <% end %>
        <% end %>
      </div>

      <div class="mt-5">
        <h4>Car Availability</h4>
        <% if !@car.availabilities.empty? %>

          <table class="table">
            <thead class="thead-dark">
              <tr>
              <th scope="col">From</th>
              <th scope="col">To</th>
              <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
            <% @car.availabilities.each do |a| %>
              <tr bgcolor="#f7f7f9" >
              <% if a.status == "Available"%>
              <td><%= a.start %></td>
              <td><%= a.end %></td>
              <td><%= a.status %></td>
              <% end %>
            <% end %>
            </tbody>
          </table>
        </div>
      
      <% else %>

        <p class="lead text-center">This car has no available dates.</p>
        <!--
          <%= link_to 'Generate Contract', new_contract_path(id: @car) %> |
          <%= link_to 'Back', browse_vehicles_path %>|
          <%= link_to "History", car_history_path(id: @car) %>
        -->

      <% end %>

      <div class="links text-center">
        <% if @car.owner != current_user %>
          <%= link_to 'Generate Contract', new_contract_path(id: @car) %> |
        <% end %>
        <%= link_to 'Back', browse_vehicles_path %>
      </div>

    </div>
  </div>
</div>
      

app/views/cars/edit.html.erb
<div class="container mb-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
        <h2 class="text-center">Update a Car</h2>

        <%= render 'form', car: @car %>

        <div class="links text-center">
            <%= link_to 'Show', @car %> |
            <%= link_to 'Remove Car', @car, method: :delete, data: { confirm: 'Are you sure you want to permanently remove this vehicle?' } %> |
            <%= link_to 'Back', cars_path %>
        </div>
    </div>
  </div>
</div>

app/views/cars/history.html.erb
<p id="notice"><%= notice %></p>

<h1><center>History</center></h1>


<style>
     table, th, td {
         text-align: center;
     }
</style>


<center>
     <table>
       <thead>
          <tr bgcolor="#c1cdcd">
               <th colspan="5"> Car: <%=@car.make_model%></th>
               <th colspan="5"> Owner: <%=@car.owner.email%></th>
            </tr>
          <tr bgcolor="#c1cdcd">
              <th>Contract ID </th>
              <th>Rental Start Date</th>
              <th>Rental Return Date</th>
              <th>Price/Day</th>
              <th>Owner Email</th>
              <th>Rental Total</th>
              <th>User Review</th>
         </tr>


       </thead>
       <tbody>

         <% @contracts.each do |contract| %>
          <tr bgcolor="#e0eeee" >
               <%if current_user == contract.car.owner %>
                    <%if @car == contract.car%>
                         <% @ctr = 1 %>
                         <% @p = @p +1 %>
                         <td><%= link_to contract.id, contract %></td>
                         <td><%= contract.start_date %></td>
                         <td><%= contract.return_date %></td>
                         <td><%= contract.price %></td>
                         <td><%= contract.car.owner.email %></td>
                         <td><%= contract.total %></td>
                         <% @rate_renter.each do |rate_renter|%>
                              <% if rate_renter.contract.id == contract.id%>
                                   <td> <div class='star-rating' data-score = <%= rate_renter.rating %>></div></td>
                              <%end%>
                         <%end%>


                    <% elsif @ctr == 0 and  @p ==@contracts.length %>
                         <% @ctr = 1 %>
                         <td>N/A</td>
                         <td>N/A</td>
                         <td>N/A</td>
                         <td>N/A</td>
                         <td>N/A</td>
                         <td>N/A</td>
                         <td>N/A</td>

                    <% end %>
               <% end %>
          </tr>
         <% end %>
       </tbody>
     </table>

</center>

<br>

<script>
     $('.star-rating').raty({
     path: '/assets/',
     readOnly: true,
     score: function() {
            return $(this).attr('data-score');
     }
     });
</script>

app/views/cars/index.html.erb
<div class="container mb-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <h2 class="text-center">My Vehicles</h2>
      
      <div class="links text-center mb-3">
        <% if @cars.empty?%>
          <p>You have not listed any vehicles for rent <em>yet</em>.</p>
        <% end %>
        <%= link_to 'Add a Vehicle', new_car_path %>
        <br>
        <%= link_to 'Set Car Availability', my_carstatus_path  %>
      </div>

      <div class="container">
        <div class="row justify-content-center">
          <% @cars.each do |car| %>
            <div class="card col-md-4 mb-3 px-1">
              <img class="card-img-top" src=<%= image_path('car_profile.jpg')%> alt="Car image placeholder">
              <div class="card-body text-center">
                <h5 class="card-title"><%= link_to car.make_model, car %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= car.year %></h6>
                <p class="card-text"><%= car.color %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container mb-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
        <h2 class="text-center">Add a Car</h2>

        <%= render 'form', car: @car %>

      <div class="links text-center">
        <%= link_to 'Back', cars_path %>
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">

      <h2 class="text-center"><%= @car.make_model_year %></h2>

      <p>
        <strong>Category:</strong>
        <%= @car.category %>
      </p>

      <p>
        <strong>Color:</strong>
        <%= @car.color %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @car.description %>
      </p>

      <p>
        <strong>Mileage:</strong>
        <%= @car.mileage %>
      </p>

      <p>
        <strong>Number of seats:</strong>
        <%= @car.number_of_seats %>
      </p>

      <p>
        <strong>Price per day: $</strong>
        <%= @car.price_per_day %>
      </p>

      <div class="mt-5">
        <h4 class="text-center">Pickup Location</h4>
        <% @car.locations.each do |location| %>
          <p>
            <%= location.address.street1 %><br>
            <%= location.address.short_form %>
          </p>
          <p>
            <strong>Status:</strong>
            <%= location.status %>
          </p>
          <br>
        <% end %>
      </div>

      <div class="links text-center">
        <%= link_to 'Edit', edit_car_path(@car) %> |
        <%= link_to 'Back', cars_path %>
      </div>

    </div>
  </div>
</div>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %> |
<%= link_to "History", car_history_path(id: @car) %>